### ISSUE TITLE
return route after sending mail ?

### ISSUE THREAD

**Issue by thomthom33** [975L/ContactFormBundle#5]
hi, once overrided email layout, works fine, thank you ! but form still displayed....
This is a question : is there a way to invoke a route after email sending ?
Alain

**Comment by Laurent3170** [comment]
The session variable `redirectUrl` is the one used to redirect, so we can define it, but it was not "easy" to modify this variable, as it is defined via `$contactFormService->defineReferer();`.
To be able to do so, I have added the `Request` to the event (v1.9.4), so now you can catch `ContactFormEvent::SEND_FORM` with the following code:

```php
namespace AppBundle\Listener;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use c975L\ContactFormBundle\Event\ContactFormEvent;

class ContactFormListener implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return array(
            ContactFormEvent::SEND_FORM => 'sendForm',
        );
    }

    public function sendForm($event)
    {
        //Updates url to redirect
        $event>getRequest()->getSession()->set('redirectUrl', 'https://example.com');
        }
    }
}
```

**Comment by Laurent3170** [comment]
As I think it's more logical, I've moved the `defineReferer()` call at the top of `ContactFormController->display()` So you can now catch the event `ContactFormEvent::CREATE_FORM` (in place of `SEND_FORM`), that's the case documented in the README.md.

**Comment by thomthom33** [comment]
hi,
i've declared the listener according your documentation, but symfony profiler says
![capture du 2018-07-31 14-59-30](https://user-images.githubusercontent.com/39346678/43460930-612cfe22-94d2-11e8-9d38-b51536623c05.png)
 it is not called.... contact form is not replaced by precedent view... i must precise /contact is called from knpmenubundle, and i've updated to your last release of contactform (sf 3.413)
Alain

**Comment by Laurent3170** [comment]
Yes you're right! The event is not dispatched...
I've found the reason. It's because before I was using `$dispatcher = $this->get('event_dispatcher')` but I've moved to `$dispatcher = new EventDispatcher();' to avoid use of `$this->get()` but it doesn't dispatch anymore...
I have to fix it, unless you want to make a PR.

I have also mixed in my mind Listener and Subscriber, I will also correct it in the README.md.
Thanks

**Comment by thomthom33** [comment]
i'm totally noob on PR, i'm waiting for you to fix it :-)

**Comment by Laurent3170** [comment]
I was (and always am) a noob for PRs and other matters. I learn by making ;-)
You can find useful information for [PRs](https://help.github.com/articles/about-pull-requests/).
PR #7 is the first that I submit containing 2 commits, I didn't know how to do before. You can have a look at it, as it's not a big one, then you can learn if you want.

Concerning the solution, in fact I had to inject EventDispatcherInterface. That's solved with v1.9.5.1

**Comment by thomthom33** [comment]
sorry but a i have an error when updating via composer, see screenshot,
![capture du 2018-08-01 20-08-40](https://user-images.githubusercontent.com/39346678/43540071-f9f5ecfa-95c6-11e8-9a2d-8e527190b0ea.png)

**Comment by Laurent3170** [comment]
Doing too many things at the same time...
It was a missing folder in 975L/EmailBundle, now solved with https://github.com/975L/EmailBundle/pull/2
Thanks

**Comment by thomthom33** [comment]
tested Ok, thanks !

**Comment by Laurent3170** [comment]
Thanks for the link on PRs that answered me a question on how to treat the PRs on the maintainer’s side :-)

**Comment by AlainT** [comment]
you're welcome !
